export default {
  login: 'Login',
  regist: 'Registo',
  confirm: 'Confirmar',
  goback: 'Voltar',
  guest: 'Entre como Guest',
  forgot: 'Esqueceu-se da sua',
  password: ' Palavra-Passe',
  no_account: 'Não tem conta?',
  regist_here: 'Registe-se aqui',
  terms: 'Aceito os Termos e Condições',
  welcome: 'Bem-vindo à Virtual Tour de',
  advance: 'Avançar para o Tour',
  choose_tour: 'Choose your tour',
  recover: 'Recuperar Password',
  recover_success: 'Foi enviado um email',
}
